//! Cumulative royalty earnings tracking.
//!
//! Tracks the total amount of royalty earnings generated by each NFT token
//! (issue #835) and by each creator / recipient address (issue #834).
//!
//! # Storage
//! - Key: `DataKey::RoyaltyEarnings(TokenId)` → `i128` (persistent)
//! - Key: `DataKey::CreatorEarnings(Address)` → `i128` (persistent)

use soroban_sdk::{Address, Env};

use crate::types::{DataKey, Error, TokenId};

/// Retrieve the cumulative royalty earnings for a token.
/// Returns `0` if no earnings have been recorded yet.
pub fn get_cumulative_earnings(env: &Env, token_id: TokenId) -> i128 {
    env.storage()
        .persistent()
        .get(&DataKey::RoyaltyEarnings(token_id))
        .unwrap_or(0)
}

/// Increment the cumulative royalty earnings for a token.
/// Prevents overflow by returning an error if the increment would exceed `i128::MAX`.
pub fn increment_earnings(env: &Env, token_id: TokenId, amount: i128) -> Result<(), Error> {
    if amount < 0 {
        return Err(Error::InvalidSalePrice);
    }

    let current = get_cumulative_earnings(env, token_id);
    let new_total = current.checked_add(amount).ok_or(Error::RoyaltyOverflow)?;

    env.storage()
        .persistent()
        .set(&DataKey::RoyaltyEarnings(token_id), &new_total);

    Ok(())
}

/// Retrieve the cumulative royalty earnings accrued by a creator / recipient.
/// Returns `0` if no earnings have been recorded yet.
pub fn get_creator_earnings(env: &Env, creator: &Address) -> i128 {
    env.storage()
        .persistent()
        .get(&DataKey::CreatorEarnings(creator.clone()))
        .unwrap_or(0)
}

/// Increment the cumulative royalty earnings for a creator / recipient.
/// Prevents overflow by returning an error if the increment would exceed `i128::MAX`.
pub fn increment_creator_earnings(env: &Env, creator: &Address, amount: i128) -> Result<(), Error> {
    if amount < 0 {
        return Err(Error::InvalidSalePrice);
    }

    let current = get_creator_earnings(env, creator);
    let new_total = current.checked_add(amount).ok_or(Error::RoyaltyOverflow)?;

    env.storage()
        .persistent()
        .set(&DataKey::CreatorEarnings(creator.clone()), &new_total);

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_to_zero() {
        let env = Env::default();
        assert_eq!(get_cumulative_earnings(&env, 1), 0);
    }

    #[test]
    fn increments_correctly() {
        let env = Env::default();
        increment_earnings(&env, 1, 100).unwrap();
        assert_eq!(get_cumulative_earnings(&env, 1), 100);

        increment_earnings(&env, 1, 50).unwrap();
        assert_eq!(get_cumulative_earnings(&env, 1), 150);
    }

    #[test]
    fn prevents_overflow() {
        let env = Env::default();
        increment_earnings(&env, 1, i128::MAX - 10).unwrap();

        let result = increment_earnings(&env, 1, 11);
        assert_eq!(result, Err(Error::RoyaltyOverflow));
    }

    #[test]
    fn rejects_negative_amounts() {
        let env = Env::default();
        let result = increment_earnings(&env, 1, -50);
        assert_eq!(result, Err(Error::InvalidSalePrice));
    }

    #[test]
    fn creator_earnings_defaults_to_zero() {
        let env = Env::default();
        let creator = soroban_sdk::testutils::Address::generate(&env);
        assert_eq!(get_creator_earnings(&env, &creator), 0);
    }

    #[test]
    fn creator_earnings_increments_and_accumulates() {
        let env = Env::default();
        let creator = soroban_sdk::testutils::Address::generate(&env);

        increment_creator_earnings(&env, &creator, 250).unwrap();
        increment_creator_earnings(&env, &creator, 250).unwrap();

        assert_eq!(get_creator_earnings(&env, &creator), 500);
    }

    #[test]
    fn creator_earnings_prevents_overflow() {
        let env = Env::default();
        let creator = soroban_sdk::testutils::Address::generate(&env);

        increment_creator_earnings(&env, &creator, i128::MAX - 5).unwrap();
        let result = increment_creator_earnings(&env, &creator, 6);
        assert_eq!(result, Err(Error::RoyaltyOverflow));
    }
}
